Declare beforeCommit plugin to control commits
tonyfromundefined/eventive pull request #2
Opened 2024-01-20 17:39 UTC by irrationnelle

Hello,

I've implemented a `beforeCommit` function to ensure data integrity during command operations like create or update in our commit process. This function facilitates writing to the database only after successful validation.

The `beforeCommit` plugin operates as follows: it validates the contents of an event body before proceeding with the commit. This is demonstrated in the code snippet below:

```typescript
eventive({
    db,
    entityName: “foo",
    reducer: fooReducer,
    plugins: [
      {
        beforeCommit({ event, entity, abortCommit }) {
          if (event.body.fooValue.includes(“invalidValue”)) {
            abortCommit()
          }
        },
      },
    ],
  })
```

In this setup, if the `event.body.fooValue` contains the string `"invalidValue"`, the commit is aborted to prevent the entry of invalid data into the database. This ensures that only validated and correct data is committed.

2024-01-22 02:30 UTC, tonyfromundefined requested changes

2024-01-22 02:30 UTC, tonyfromundefined commented on packages/eventive/src/EventivePlugin.ts
> +    abortCommit: () => void;
```suggestion
    abort: () => void;
```

I think `abort` is more consistent naming

2024-01-22 02:36 UTC, tonyfromundefined commented
I think it would be better to handle it with a throw rather than abort.

2024-01-22 03:35 UTC, irrationnelle commented
d76fb43983589ad2904424ab051ece69a6587042

I followed your suggestion

2024-01-29 03:58 UTC, tonyfromundefined approved these changes

2024-01-29 03:58 UTC, merged